py27 recreate: /home/stack/openstack/omni/.tox/py27
ERROR: invocation failed (exit code 3), logfile: /home/stack/openstack/omni/.tox/py27/log/py27-0.log
ERROR: actionid: py27
msg: getenv
cmdargs: ['/usr/bin/python', '-m', 'virtualenv', '--python', '/usr/bin/python2.7', 'py27']
env: {'VIRTUAL_ENV': '/home/stack/openstack/omni/.tox/py27', 'SHLVL': '1', 'LANG': 'en_US.UTF-8', 'PATH': '/home/stack/openstack/omni/.tox/py27/bin:/home/stack/openstack/omni/.tox/py27/bin:/home/stack/bin:/home/stack/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'PWD': '/home/stack/openstack/omni', 'PYTHONHASHSEED': '756525180', '_': '/usr/local/bin/tox', 'LANGUAGE': 'en_US'}


ERROR: InvocationError: /usr/bin/python -m virtualenv --python /home/stack/openstack/omni/.tox/py27/bin/python2.7 py27 (see /home/stack/openstack/omni/.tox/py27/log/py27-0.log)
___________________________________ summary ____________________________________
ERROR:   py27: InvocationError: /usr/bin/python -m virtualenv --python /home/stack/openstack/omni/.tox/py27/bin/python2.7 py27 (see /home/stack/openstack/omni/.tox/py27/log/py27-0.log)
